spring:
  application:
    name: ms-student
  h2:
    console:
      enabled: true
server:
  port: 6945

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
  instance:
    prefer-ip-address: true
